# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoose',
            name='restrict',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
