# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160401_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernutrition',
            old_name='fat',
            new_name='fats',
        ),
    ]
