# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 17:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160401_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutrition',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 4, 11, 17, 54, 6, 222875, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
