# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usernutrition_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anthony', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('calories', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('meals', models.IntegerField(default=0)),
                ('freeCal', models.IntegerField(default=0)),
                ('want', models.CharField(default='none', max_length=100)),
                ('noWant', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserNutrition',
        ),
    ]
