# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('measurement', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('net_carb', models.IntegerField(default=0)),
                ('carb', models.IntegerField(default=0)),
                ('fiber', models.IntegerField(default=0)),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.FridgeItem')),
            ],
        ),
    ]
