# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemnutrition',
            name='i',
        ),
        migrations.RenameField(
            model_name='fridgeitem',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='fiber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='servings',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ItemNutrition',
        ),
    ]
