# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ketoBot', '0005_ingredient_rawstring'),
        ('fridge', '0002_auto_20160426_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField(default=1)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.FridgeItem')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('adherence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('servings', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('eaten', models.BooleanField(default=0)),
                ('fridgeRef', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='fridge.FridgeItem')),
                ('mealPlanRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.MealPlan')),
                ('recipeRef', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ketoBot.Recipe')),
            ],
        ),
    ]
