# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_fridgefill_mealplan_mealplanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanitem',
            name='typeof',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
    ]
