# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0007_auto_20160524_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='eaten',
            field=models.IntegerField(default=0),
        ),
    ]
