# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0008_auto_20160524_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eaten', models.BooleanField(default=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.FridgeItem')),
            ],
        ),
    ]
