# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0009_fridgeinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridgeinventory',
            old_name='item_id',
            new_name='fridgeItem',
        ),
    ]
