# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Ingred_Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('net_carb', models.IntegerField(default=0)),
                ('carb', models.IntegerField(default=0)),
                ('fiber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('measurement', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Directions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_step', models.CharField(max_length=200)),
                ('direction_picture', models.CharField(max_length=200)),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketoBot.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('carb', models.IntegerField(default=0)),
                ('fiber', models.IntegerField(default=0)),
                ('net_carb', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketoBot.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketoBot.Recipe'),
        ),
        migrations.AddField(
            model_name='ingred_nutrition',
            name='i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketoBot.Ingredient'),
        ),
    ]
