# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketoBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_date',
            field=models.CharField(max_length=200),
        ),
    ]
