# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ketoBot', '0002_auto_20160309_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(default=datetime.datetime(2016, 3, 9, 23, 12, 49, 711253, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
