# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketoBot', '0003_recipe_recipe_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingred_nutrition',
            old_name='ingredient',
            new_name='i',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe_id',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='recipe_directions',
            old_name='recipe_id',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='recipe_nutrition',
            old_name='recipe_id',
            new_name='r',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
