# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketoBot', '0004_auto_20160310_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
