# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketoBot', '0004_recipe_staple'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='rawString',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
