# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketoBot', '0005_auto_20160310_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_title',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_type',
            new_name='title',
        ),
        migrations.AddField(
            model_name='recipe_nutrition',
            name='servings',
            field=models.IntegerField(default=0),
        ),
    ]
